### ISSUE TITLE
Where is the lowes and home depot files?

### ISSUE THREAD

**Issue by ninko76** [jimilinuxguy/customer-assistance-buttons-sdr#4]
This gitgub advertizes "Walgreens, CVS, Lowes, and Home Depot" and I can only see CVS. Is this a problem on my end? Or were they taken down?

**Comment by RocketGod-git** [comment]
Other files are already in my repo for those... he just hasen't expanded on those ones yet. 😋

**Comment by UberGuidoZ** [comment]
[Also here](https://github.com/UberGuidoZ/Flipper/tree/main/Sub-GHz/Customer_Assistance_Buttons) =)

**Comment by batrachophagous1** [comment]
@UberGuidoZ what about home depot?

**Comment by UberGuidoZ** [comment]
If you have verified files, I'll happily add them!

**Comment by batrachophagous1** [comment]
@UberGuidoZ  I'm asking cuz I heard there were home Depot files, that's what the repo's description says

**Comment by UberGuidoZ** [comment]
You should ask @jimilinuxguy instead then - everything I have is in my repo!

**Comment by jimilinuxguy** [comment]
I lost the device that had my files on it.
